"""Pure-stdlib cryptographic primitives for the auth layer.

Two things live here:

* ``hash_password`` / ``verify_password`` -- salted ``scrypt`` password
  hashing.  The digest string is self-describing (``scrypt$n$r$p$salt$hash``)
  and the plaintext never appears in it.
* Minimal RSA key generation, PKCS#1 v1.5 (SHA-256) signing/verification, and
  OpenSSH wire-format (de)serialisation.  This is enough to *verify* an
  ``authorized_keys``-style RSA public key against a signature produced by an
  SSH client -- no third-party crypto dependency.

RSA verification uses only ``pow`` (modular exponentiation) plus ``hashlib``.
Key *generation* is provided so tests and offline setup can mint key pairs
without a dependency; production deployments should register keys produced by
``ssh-keygen`` (2048 bits or stronger), which this module verifies identically.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import math
import secrets
import struct
from typing import Any

# ---------------------------------------------------------------------------
# Password hashing (scrypt)
# ---------------------------------------------------------------------------

_SCRYPT_N = 2**14
_SCRYPT_R = 8
_SCRYPT_P = 1
_SALT_BYTES = 16


def hash_password(password: str, *, salt: bytes | None = None) -> str:
    """Hash ``password`` with a fresh random salt and return a digest string.

    The returned string is ``scrypt$n$r$p$<salt_b64>$<hash_b64>``.  It carries
    no reversible form of the password.
    """
    if not isinstance(password, str):
        raise TypeError("password must be a string")
    pw = password.encode("utf-8")
    salt = salt if salt is not None else secrets.token_bytes(_SALT_BYTES)
    dk = hashlib.scrypt(pw, salt=salt, n=_SCRYPT_N, r=_SCRYPT_R, p=_SCRYPT_P)
    return "scrypt$%d$%d$%d$%s$%s" % (
        _SCRYPT_N,
        _SCRYPT_R,
        _SCRYPT_P,
        base64.b64encode(salt).decode("ascii"),
        base64.b64encode(dk).decode("ascii"),
    )


def verify_password(password: str, stored: str) -> bool:
    """Return ``True`` iff ``password`` matches the stored scrypt digest.

    Parses the self-describing digest so parameters can be tuned later without
    invalidating existing records.  Comparison is constant-time.
    """
    if not isinstance(password, str) or not isinstance(stored, str):
        return False
    parts = stored.split("$")
    if len(parts) != 6 or parts[0] != "scrypt":
        return False
    try:
        n, r, p = int(parts[1]), int(parts[2]), int(parts[3])
        salt = base64.b64decode(parts[4])
        expected = base64.b64decode(parts[5])
    except (ValueError, TypeError):
        return False
    try:
        dk = hashlib.scrypt(password.encode("utf-8"), salt=salt, n=n, r=r, p=p)
    except ValueError:
        return False
    return hmac.compare_digest(dk, expected)


# ---------------------------------------------------------------------------
# RSA (PKCS#1 v1.5, SHA-256)
# ---------------------------------------------------------------------------

_DIGEST_INFO_SHA256 = bytes.fromhex(
    "3031300d060960864801650304020105000420"
)
_SHA256 = hashlib.sha256

_RSA_E = 65537


def _is_probable_prime(n: int) -> bool:
    """Miller-Rabin primality test (deterministic for small ints, else strong)."""
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d = n - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53):
        if a >= n:
            continue
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


def _generate_prime(bits: int) -> int:
    while True:
        candidate = secrets.randbits(bits) | (1 << (bits - 1)) | 1
        if _is_probable_prime(candidate):
            return candidate


def generate_rsa_keypair(bits: int = 1024) -> dict[str, int]:
    """Generate an RSA key pair (``n, e, d, p, q``).

    ``bits=1024`` is offered only for fast tests; real deployments use keys
    generated by ``ssh-keygen`` at 2048+ bits.
    """
    if bits < 512:
        raise ValueError("bits must be at least 512")
    while True:
        p = _generate_prime(bits // 2)
        q = _generate_prime(bits // 2)
        if p == q:
            continue
        n = p * q
        phi = (p - 1) * (q - 1)
        if math.gcd(_RSA_E, phi) != 1:
            continue
        d = pow(_RSA_E, -1, phi)
        return {"n": n, "e": _RSA_E, "d": d, "p": p, "q": q}


def _emsa_pkcs1_v15_sha256(message: bytes, k: int) -> bytes:
    """Build the PKCS#1 v1.5 encoded message for SHA-256 (``k`` bytes)."""
    digest = _SHA256(message).digest()
    t = _DIGEST_INFO_SHA256 + digest
    if k < len(t) + 11:
        raise ValueError("intended encoded message length too short")
    ps = b"\xff" * (k - len(t) - 3)
    return b"\x00\x01" + ps + b"\x00" + t


def rsa_sign(private: dict[str, int], message: bytes) -> bytes:
    """Produce a PKCS#1 v1.5 SHA-256 signature over ``message``."""
    n = private["n"]
    k = (n.bit_length() + 7) // 8
    em = _emsa_pkcs1_v15_sha256(message, k)
    m = int.from_bytes(em, "big")
    s = pow(m, private["d"], n)
    return s.to_bytes(k, "big")


def rsa_verify(public: dict[str, int], message: bytes, signature: bytes) -> bool:
    """Verify a PKCS#1 v1.5 SHA-256 signature (constant-time comparison)."""
    n, e = public["n"], public["e"]
    k = (n.bit_length() + 7) // 8
    if len(signature) != k:
        return False
    s = int.from_bytes(signature, "big")
    if s < 0 or s >= n:
        return False
    m = pow(s, e, n)
    em = m.to_bytes(k, "big")
    expected = _emsa_pkcs1_v15_sha256(message, k)
    return hmac.compare_digest(em, expected)


# ---------------------------------------------------------------------------
# OpenSSH wire format
# ---------------------------------------------------------------------------

_SSH_RSA = b"ssh-rsa"
_SSH_RSA_SHA256 = b"rsa-sha2-256"


def _ssh_string(data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + data


def _read_string(data: bytes, offset: int) -> tuple[bytes, int]:
    (length,) = struct.unpack_from(">I", data, offset)
    offset += 4
    return data[offset : offset + length], offset + length


def _mpint_encode(value: int) -> bytes:
    if value == 0:
        return b"\x00"
    raw = value.to_bytes((value.bit_length() + 7) // 8, "big")
    if raw[0] & 0x80:
        raw = b"\x00" + raw
    return raw


def _mpint_decode(raw: bytes) -> int:
    return int.from_bytes(raw, "big", signed=False)


def serialize_ssh_public_key(public: dict[str, int], comment: str = "") -> str:
    """Encode an RSA public key as an OpenSSH ``authorized_keys`` line."""
    blob = (
        _ssh_string(_SSH_RSA)
        + _ssh_string(_mpint_encode(public["e"]))
        + _ssh_string(_mpint_encode(public["n"]))
    )
    b64 = base64.b64encode(blob).decode("ascii")
    return ("ssh-rsa " + b64 + (" " + comment if comment else "")).rstrip()


def parse_ssh_public_key(line: str) -> dict[str, int] | None:
    """Parse an ``authorized_keys`` line into ``{"n": ..., "e": ...}``.

    Returns ``None`` for anything that is not a well-formed RSA key.
    """
    if not isinstance(line, str):
        return None
    fields = line.split()
    if len(fields) < 2 or fields[0] != "ssh-rsa":
        return None
    try:
        blob = base64.b64decode(fields[1], validate=True)
    except (ValueError, TypeError):
        return None
    try:
        key_type, off = _read_string(blob, 0)
        if key_type != _SSH_RSA:
            return None
        e_raw, off = _read_string(blob, off)
        n_raw, off = _read_string(blob, off)
    except (struct.error, ValueError, IndexError):
        return None
    e = _mpint_decode(e_raw)
    n = _mpint_decode(n_raw)
    if e <= 0 or n <= 0:
        return None
    return {"n": n, "e": e}


def build_ssh_signature(private: dict[str, int], data: bytes) -> bytes:
    """Sign ``data`` with the private key and wrap it in an SSH signature blob.

    The blob is ``string "rsa-sha2-256" || string <raw signature>``, matching
    the format an SSH client emits.
    """
    sig = rsa_sign(private, data)
    return _ssh_string(_SSH_RSA_SHA256) + _ssh_string(sig)


def verify_ssh_signature(public_key_line: str, data: bytes, sig_blob: bytes) -> bool:
    """Verify an SSH signature blob against an ``authorized_keys`` line."""
    public = parse_ssh_public_key(public_key_line)
    if public is None or not isinstance(sig_blob, bytes):
        return False
    try:
        algo, off = _read_string(sig_blob, 0)
        sig, off = _read_string(sig_blob, off)
    except (struct.error, ValueError, IndexError):
        return False
    if algo not in (_SSH_RSA, _SSH_RSA_SHA256):
        return False
    return rsa_verify(public, data, sig)


def constant_time_equals(a: Any, b: Any) -> bool:
    """Compare two values in constant time (safe for secrets and non-secrets)."""
    if isinstance(a, str):
        a = a.encode("utf-8")
    if isinstance(b, str):
        b = b.encode("utf-8")
    return hmac.compare_digest(bytes(a), bytes(b))


__all__ = [
    "hash_password",
    "verify_password",
    "generate_rsa_keypair",
    "rsa_sign",
    "rsa_verify",
    "serialize_ssh_public_key",
    "parse_ssh_public_key",
    "build_ssh_signature",
    "verify_ssh_signature",
    "constant_time_equals",
]
