"""Device pairing (phase 6a).

A machine enrols itself with the panel *without anyone touching the server*,
while the decision to trust it stays entirely on the server side.  The
direction matters: the enrolling machine is never trusted to supply its own
identity.  It posts a public key and receives back a short one-time code that
was generated by the server; only the owner's later approval (protected by a
TOTP second factor) creates the authorised device.

The pairing table is a *request log*, not a device store.  Authorised devices
live in ``meshdispatch.auth``'s device store, and approval goes through the
existing ``enroll_device`` enrolment so there is exactly one source of truth.
The plaintext pairing code is returned exactly once by :func:`create_pairing`
and persisted only as a SHA-256 hash; a caller that needs to show it again
(e.g. the owner's dashboard) holds the plaintext in memory, never on disk.
"""

from __future__ import annotations

import base64
import hashlib
import secrets
import struct
from datetime import datetime, timedelta
from typing import Any, Callable

from .. import models
from ..auth.crypto import parse_ssh_public_key
from ..store import Store

#: Default lifetime of a pairing code before it can no longer be decided.
#: Shorter than an approval: this is a bootstrap, not an ongoing grant.
DEFAULT_PAIRING_TTL_SECONDS = 15 * 60

#: Unambiguous code alphabet (no 0/O/1/I/L) and length for the one-time code.
_CODE_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"
_CODE_LENGTH = 8

_PAIRING_STATUSES = ("pending", "approved", "rejected", "expired")


class PairingError(Exception):
    """Base class for pairing workflow errors."""


class PairingNotFound(PairingError):
    """The requested pairing id does not exist."""

    def __init__(self, pairing_id: str) -> None:
        self.pairing_id = pairing_id
        super().__init__(f"no such pairing: {pairing_id}")


class PairingConflict(PairingError):
    """The pairing has already been decided and cannot be decided again."""

    def __init__(self, pairing_id: str, status: str) -> None:
        self.pairing_id = pairing_id
        self.status = status
        super().__init__(f"pairing {pairing_id} is already {status}")


class PairingExpired(PairingError):
    """The pairing is past its expiry and can no longer be decided."""

    def __init__(self, pairing_id: str) -> None:
        self.pairing_id = pairing_id
        super().__init__(f"pairing {pairing_id} has expired")


class DuplicatePublicKey(PairingError):
    """A pending or approved pairing already exists for this public key."""

    def __init__(self, fingerprint: str) -> None:
        self.fingerprint = fingerprint
        super().__init__(
            f"a pairing already exists for this public key (fingerprint {fingerprint})"
        )


def _parse_ts(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _add_seconds(value: str, seconds: float) -> str:
    dt = _parse_ts(value) + timedelta(seconds=seconds)
    return models.normalize_ts(dt)


def _expired(expires_at: str, now: str) -> bool:
    return _parse_ts(now) > _parse_ts(expires_at)


def generate_pairing_id(now: datetime | None = None) -> str:
    """Build a pairing id of the form ``pr-<YYYYMMDD>-<6hex>``."""
    day = (now or models.now_utc()).strftime("%Y%m%d")
    suffix = secrets.token_hex(3)
    return f"pr-{day}-{suffix}"


def generate_pairing_code() -> str:
    """Generate a short, unambiguous one-time pairing code."""
    return "".join(secrets.choice(_CODE_ALPHABET) for _ in range(_CODE_LENGTH))


def hash_pairing_code(code: str) -> str:
    """SHA-256 hex digest of a pairing code; what actually gets persisted."""
    return hashlib.sha256(code.encode("utf-8")).hexdigest()


#: Public key types we accept for enrolment.  Deliberately a list rather than a
#: single type: ``ssh-keygen`` defaults to ed25519, so an RSA-only check rejects
#: the very keys most people have.  Verification elsewhere in this project goes
#: through ``ssh-keygen -Y verify`` (see ``meshdispatch.auth.ssh``), which handles
#: every type below, so enrolment must not be narrower than verification.
SUPPORTED_KEY_TYPES = (
    "ssh-ed25519",
    "sk-ssh-ed25519@openssh.com",
    "ssh-rsa",
    "ecdsa-sha2-nistp256",
    "ecdsa-sha2-nistp384",
    "ecdsa-sha2-nistp521",
    "sk-ecdsa-sha2-nistp256@openssh.com",
)


def _read_ssh_string(blob: bytes, offset: int) -> tuple[bytes, int]:
    """Read one length-prefixed SSH string; ``ValueError`` if truncated."""
    if offset + 4 > len(blob):
        raise ValueError("truncated key blob")
    (length,) = struct.unpack(">I", blob[offset : offset + 4])
    start = offset + 4
    end = start + length
    if end > len(blob):
        raise ValueError("truncated key blob")
    return blob[start:end], end


def validate_public_key(public_key: str) -> str:
    """Validate and normalise an ``authorized_keys`` line.

    Accepts every type in :data:`SUPPORTED_KEY_TYPES`, in the standard
    ``<type> <base64 blob> [comment]`` form, and checks that the blob's own
    embedded type string agrees with the declared one.  That structural check is
    what stops arbitrary text or a truncated blob being accepted as a key; it
    does not depend on the type being RSA.
    """
    if not isinstance(public_key, str) or not public_key.strip():
        raise ValueError("public_key is required")
    public_key = public_key.strip()
    fields = public_key.split()
    if len(fields) < 2:
        raise ValueError(
            "public_key must be an authorized_keys line: "
            "'<type> <base64 blob> [comment]'"
        )
    key_type, blob_b64 = fields[0], fields[1]
    if key_type not in SUPPORTED_KEY_TYPES:
        raise ValueError(
            f"unsupported public key type {key_type!r}; supported: "
            + ", ".join(SUPPORTED_KEY_TYPES)
        )
    try:
        blob = base64.b64decode(blob_b64, validate=True)
    except (ValueError, TypeError):
        raise ValueError("public_key blob is not valid base64") from None
    try:
        embedded, _ = _read_ssh_string(blob, 0)
    except (ValueError, struct.error):
        raise ValueError("public_key blob is not a well-formed SSH key") from None
    if embedded.decode("ascii", "replace") != key_type:
        raise ValueError(
            "public_key type does not match the type declared in its blob"
        )
    return public_key


def compute_key_fingerprint(public_key: str) -> str:
    """Return the OpenSSH-style ``SHA256:`` fingerprint of a public key line."""
    public_key = validate_public_key(public_key)
    raw = base64.b64decode(public_key.split()[1], validate=True)
    digest = hashlib.sha256(raw).digest()
    return "SHA256:" + base64.b64encode(digest).decode("ascii").rstrip("=")


def create_pairing(
    store: Store,
    *,
    public_key: str,
    display_name: str,
    ttl_seconds: int = DEFAULT_PAIRING_TTL_SECONDS,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Create a *pending* pairing request and return it with its one-time code.

    The code is generated by the server, its hash is persisted, and the
    plaintext is returned exactly once (as ``record["code"]``).  A public key
    that is already pending or approved is rejected with
    :class:`DuplicatePublicKey`.
    """
    public_key = validate_public_key(public_key)
    if not isinstance(display_name, str) or not display_name.strip():
        raise ValueError("display_name is required")
    display_name = display_name.strip()
    fingerprint = compute_key_fingerprint(public_key)

    existing = store.find_pairing_by_public_key(public_key)
    if existing is not None:
        if existing["status"] == "approved":
            raise DuplicatePublicKey(fingerprint)
        if existing["status"] == "pending":
            now_iso = models.normalize_ts(now or models.now_utc())
            if not _expired(existing["expires_at"], now_iso):
                raise DuplicatePublicKey(fingerprint)

    code = generate_pairing_code()
    pairing_id = generate_pairing_id(now)
    created = models.normalize_ts(now or models.now_utc())
    expires = _add_seconds(created, ttl_seconds)

    record = store.insert_pairing(
        pairing_id=pairing_id,
        code_hash=hash_pairing_code(code),
        code=code,
        display_name=display_name,
        public_key=public_key,
        key_fingerprint=fingerprint,
        status="pending",
        created_at=created,
        expires_at=expires,
    )
    return {**record, "code": code}


def get_pairing(store: Store, pairing_id: str) -> dict[str, Any] | None:
    return store.get_pairing(pairing_id)


def list_pairings(store: Store, status: str | None = None) -> list[dict[str, Any]]:
    return store.list_pairings(status=status)


def approve_pairing(
    store: Store,
    pairing_id: str,
    *,
    decided_by: str,
    enroll: Callable[[str, str], str],
    now: datetime | None = None,
) -> dict[str, Any]:
    """Approve a pending pairing and register the device via ``enroll``.

    ``enroll(principal, device_name) -> device_id`` must be the existing device
    enrolment from ``meshdispatch.auth``; the resulting device id is recorded on
    the pairing row.  Only a pending, unexpired entry can be approved.
    """
    return _decide(
        store, pairing_id, decision="approved", decided_by=decided_by,
        enroll=enroll, now=now,
    )


def reject_pairing(
    store: Store,
    pairing_id: str,
    *,
    decided_by: str,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Reject a pending pairing; only a pending, unexpired entry can be decided."""
    return _decide(
        store, pairing_id, decision="rejected", decided_by=decided_by,
        enroll=None, now=now,
    )


def _decide(
    store: Store,
    pairing_id: str,
    *,
    decision: str,
    decided_by: str,
    enroll: Callable[[str, str], str] | None,
    now: datetime | None = None,
) -> dict[str, Any]:
    if not isinstance(decided_by, str) or not decided_by.strip():
        raise ValueError("decided_by is required")
    decided_by = decided_by.strip()

    current = store.get_pairing(pairing_id)
    if current is None:
        raise PairingNotFound(pairing_id)
    if current["status"] != "pending":
        raise PairingConflict(pairing_id, current["status"])

    now_iso = models.normalize_ts(now or models.now_utc())
    if _expired(current["expires_at"], now_iso):
        store.set_pairing_decision(
            pairing_id, status="expired", decided_at=now_iso
        )
        raise PairingExpired(pairing_id)

    device_id: str | None = None
    if decision == "approved":
        assert enroll is not None
        device_id = enroll(decided_by, current["display_name"])

    return store.set_pairing_decision(
        pairing_id,
        status=decision,
        decided_at=now_iso,
        decided_by=decided_by,
        device_id=device_id,
    )


# ---------------------------------------------------------------------------
# Auth-manager adapters (one source of truth for authorised devices)
# ---------------------------------------------------------------------------


def device_enroller_from_manager(manager: Any) -> Callable[[str, str], str]:
    """Build an ``(principal, device_name) -> device_id`` enroller from auth.

    Enrolment goes through :meth:`~meshdispatch.auth.AuthManager.enroll_device`
    and is then confirmed so the freshly paired device is immediately usable.
    """

    def enroll(principal: str, device_name: str) -> str:
        device_id = manager.enroll_device(principal, device_name=device_name)
        manager.confirm_device(device_id, approver_principal=principal)
        return device_id

    return enroll


def device_lister_from_manager(manager: Any) -> Callable[..., list[dict[str, Any]]]:
    """Build a device lister that reads auth's device store."""

    def list_devices(principal: str | None = None) -> list[dict[str, Any]]:
        return manager.store.list_devices(principal)

    return list_devices


def device_revoker_from_manager(manager: Any) -> Callable[[str], bool]:
    """Build a device revoker that un-confirms a device in auth's store.

    Delegates to :meth:`~meshdispatch.auth.AuthManager.revoke_device`; auth's
    device layer refuses unconfirmed devices, so this deauthorises the device
    without deleting the audit trail.
    """

    def revoke(device_id: str) -> bool:
        revoke_device = getattr(manager, "revoke_device", None)
        if callable(revoke_device):
            return bool(revoke_device(device_id))
        # Backwards compatible with managers that predate ``revoke_device``.
        rec = manager.store.get_device(device_id)
        if rec is None:
            return False
        rec["confirmed"] = False
        rec["confirmed_at"] = None
        rec["confirmed_by"] = None
        manager.store.set_device(device_id, rec)
        return True

    return revoke


__all__ = [
    "DEFAULT_PAIRING_TTL_SECONDS",
    "DuplicatePublicKey",
    "PairingConflict",
    "PairingError",
    "PairingExpired",
    "PairingNotFound",
    "approve_pairing",
    "compute_key_fingerprint",
    "create_pairing",
    "device_enroller_from_manager",
    "device_lister_from_manager",
    "device_revoker_from_manager",
    "generate_pairing_code",
    "generate_pairing_id",
    "get_pairing",
    "hash_pairing_code",
    "list_pairings",
    "reject_pairing",
    "validate_public_key",
]
